# Generated by Django 6.1 on 2026-08-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoprompt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprompt',
            name='comments_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoprompt',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoprompt',
            name='likes_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoprompt',
            name='upload_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videoprompt',
            name='uploader_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videoprompt',
            name='views_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
