# Generated by Django 6.1 on 2026-09-18 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoprompt', '0002_videoprompt_comments_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeminiAPIKey',
        ),
    ]
