# Generated by Django 6.1 on 2026-08-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_can_manage_api_keys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_fanpages',
            field=models.BooleanField(default=True, help_text='Acceso a Fanpage Creator'),
        ),
    ]
