# Generated by Django 6.1 on 2026-09-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_id_alter_userprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_ig_downloader',
            field=models.BooleanField(default=True, help_text='Acceso a IG Downloader'),
        ),
    ]
