# Generated by Django 6.1 on 2026-09-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_can_view_ig_downloader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='can_manage_api_keys',
        ),
    ]
