services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - SQLITE_PATH=/app/data/db.sqlite3
    volumes:
      - media_volume:/app/media
      - db_volume:/app/data

volumes:
  media_volume:
  db_volume:
