services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=*
    volumes:
      - media_volume:/app/media

volumes:
  media_volume:
