# Generated by Django 6.1 on 2026-08-30 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FanpageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre creativo de la fanpage en español', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción y gancho de la fanpage')),
                ('prompt_foto_perfil', models.TextField(help_text='Prompt en inglés para foto de perfil (1:1)')),
                ('prompt_foto_portada', models.TextField(help_text='Prompt en inglés para portada panorámica (16:5)')),
                ('estilo_visual', models.CharField(help_text='Estilo artístico visual', max_length=200)),
                ('subtema', models.CharField(help_text='Subtema o nicho específico', max_length=200)),
                ('modelo_usado', models.CharField(default='google/gemini-2.5-flash', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fanpage_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fanpage Profile',
                'verbose_name_plural': 'Fanpage Profiles',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
