# Generated by Django 6.1 on 2026-09-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRouterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='API Key de OpenRouter (sk-or-v1-...)', max_length=255)),
                ('model_name', models.CharField(default='google/gemini-2.5-flash', help_text='Identificador del modelo en OpenRouter (ej. google/gemini-2.5-flash)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Habilita o deshabilita el uso de esta clave')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración OpenRouter',
                'verbose_name_plural': 'Configuraciones OpenRouter',
                'ordering': ['-updated_at'],
            },
        ),
    ]
