# Generated by Django 6.1 on 2026-09-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpages', '0002_openrouterconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openrouterconfig',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Configuración de IA para Fanpages', 'verbose_name_plural': 'Configuraciones de IA para Fanpages'},
        ),
        migrations.AddField(
            model_name='openrouterconfig',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='API Key dedicada de Google AI Studio (opcional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='openrouterconfig',
            name='gemini_model',
            field=models.CharField(default='gemini-2.5-flash', help_text='Modelo de Gemini (ej. gemini-2.5-flash, gemini-2.0-flash)', max_length=100),
        ),
        migrations.AddField(
            model_name='openrouterconfig',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini Directo'), ('openrouter', 'OpenRouter')], default='gemini', help_text='Proveedor de IA activo para Fanpages', max_length=20),
        ),
        migrations.AddField(
            model_name='openrouterconfig',
            name='use_gemini_pool',
            field=models.BooleanField(default=True, help_text='Usar automáticamente el pool de claves de Gemini si no hay clave dedicada'),
        ),
        migrations.AlterField(
            model_name='openrouterconfig',
            name='api_key',
            field=models.CharField(blank=True, help_text='API Key de OpenRouter (sk-or-v1-...)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='openrouterconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Habilita o deshabilita la IA en Fanpages'),
        ),
    ]
