# Generated by Django 6.1 on 2026-09-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanpages', '0003_alter_openrouterconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanpageprofile',
            name='modelo_usado',
            field=models.CharField(default='gemini-3.6-flash', max_length=100),
        ),
        migrations.AlterField(
            model_name='openrouterconfig',
            name='gemini_model',
            field=models.CharField(default='gemini-3.6-flash', help_text='Modelo de Gemini (ej. gemini-3.6-flash, gemini-3.5-flash)', max_length=100),
        ),
    ]
