# Generated by Django 5.2.16 on 2026-08-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FanpageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prompt_foto_perfil', models.TextField()),
                ('prompt_foto_portada', models.TextField()),
                ('estilo_visual', models.CharField(max_length=200)),
                ('subtema', models.CharField(max_length=200)),
                ('modelo_usado', models.CharField(default='google/gemini-2.5-flash', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fanpage Profile',
                'verbose_name_plural': 'Fanpage Profiles',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
