# Generated by Django 6.1 on 2026-08-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_prompt_limit',
            field=models.PositiveIntegerField(default=10, help_text='Límite diario de prompts'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_unlimited_prompts',
            field=models.BooleanField(default=False, help_text='Permite generación ilimitada de prompts'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
