# Generated by Django 6.1 on 2026-08-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_daily_prompt_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_manage_api_keys',
            field=models.BooleanField(default=False, help_text='Permiso para gestionar el pool de API Keys'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_users',
            field=models.BooleanField(default=False, help_text='Permiso para administrar usuarios'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_dashboard',
            field=models.BooleanField(default=True, help_text='Acceso al Dashboard general'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_stats',
            field=models.BooleanField(default=True, help_text='Acceso a la pestaña de estadísticas y métricas del Reel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_videoprompt',
            field=models.BooleanField(default=True, help_text='Acceso a Video to Prompt Studio'),
        ),
    ]
