# Generated by Django 5.2.16 on 2026-08-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_can_view_fanpages'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_extractor',
            field=models.BooleanField(default=True, help_text='Acceso a Facebook Fan Extractor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
