# Generated by Django 6.1 on 2026-08-30 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='API Key de Google AI Studio', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Activar/Desactivar esta clave manualmente')),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('error_count', models.IntegerField(default=0, editable=False)),
                ('status_message', models.CharField(default='Activa', help_text='Estado reportado por el rotador', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gemini API Key',
                'verbose_name_plural': 'Gemini API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='uploaded_videos/')),
                ('additional_context', models.TextField(blank=True, null=True)),
                ('prompt_language', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('pt', 'Portugués'), ('fr', 'Francés')], default='es', max_length=10)),
                ('generated_prompt', models.TextField(blank=True, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnails/')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Prompt',
                'verbose_name_plural': 'Video Prompts',
                'ordering': ['-created_at'],
            },
        ),
    ]
