# Generated by Django 6.1 on 2026-09-12 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('uploader', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='ig_thumbnails/')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('direct_video_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instagram Download',
                'verbose_name_plural': 'Instagram Downloads',
                'ordering': ['-created_at'],
            },
        ),
    ]
