# Generated by Django 6.1 on 2026-09-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdownloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramdownload',
            name='fb_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramdownload',
            name='fb_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramdownload',
            name='fb_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramdownload',
            name='fb_hashtags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instagramdownload',
            name='fb_status',
            field=models.CharField(choices=[('idle', 'Sin generar'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='instagramdownload',
            name='fb_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
