# Generated by Django 6.1 on 2026-09-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdownloader', '0002_instagramdownload_fb_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramdownload',
            name='fb_hashtags_source',
            field=models.CharField(choices=[('original', 'Originales de Instagram'), ('ai', 'Generados por IA')], default='original', max_length=20),
        ),
        migrations.AddField(
            model_name='instagramdownload',
            name='original_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramdownload',
            name='original_hashtags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
