# Generated by Django 6.1 on 2026-09-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdownloader', '0003_instagramdownload_fb_hashtags_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramdownload',
            name='comment_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramdownload',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
