# Generated by Django 6.1 on 2026-09-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordPressSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del sitio WordPress', max_length=150, verbose_name='Nombre del Sitio')),
                ('site_url', models.URLField(help_text='URL raíz del sitio (ej: https://midominio.com)', max_length=255, unique=True, verbose_name='URL del Sitio')),
                ('username', models.CharField(help_text='Usuario de WordPress con permisos de publicación', max_length=100, verbose_name='Usuario WordPress')),
                ('application_password', models.CharField(help_text='Contraseña de aplicación generada en WordPress', max_length=255, verbose_name='Contraseña de Aplicación')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el sitio está habilitado en el pool para publicación', verbose_name='Activo')),
                ('posts_published_count', models.PositiveIntegerField(default=0, help_text='Cantidad total de posts publicados en este sitio', verbose_name='Artículos Publicados')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Uso')),
                ('last_status', models.CharField(choices=[('untested', 'Sin probar'), ('connected', 'Conectado OK'), ('error', 'Error de conexión')], default='untested', max_length=50, verbose_name='Estado de Conexión')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Último Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Dominio WordPress',
                'verbose_name_plural': 'Dominios WordPress',
                'ordering': ['-created_at'],
            },
        ),
    ]
