# Generated by Django 5.2.16 on 2026-08-30 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractorSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Extractor Setting',
                'verbose_name_plural': 'Extractor Settings',
            },
        ),
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En ejecución'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('total_urls', models.PositiveIntegerField(default=0)),
                ('processed_urls', models.PositiveIntegerField(default=0)),
                ('successful_urls', models.PositiveIntegerField(default=0)),
                ('failed_urls', models.PositiveIntegerField(default=0)),
                ('raw_input', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extraction Job',
                'verbose_name_plural': 'Extraction Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=500)),
                ('name', models.CharField(blank=True, default='Desconocido', max_length=255)),
                ('followers', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(default='Pendiente', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facebook Page',
                'verbose_name_plural': 'Facebook Pages',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('followers', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(max_length=255)),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='extractor.extractionjob')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='extractor.facebookpage')),
            ],
            options={
                'verbose_name': 'Extraction Item',
                'verbose_name_plural': 'Extraction Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='facebookpage',
            constraint=models.UniqueConstraint(fields=('user', 'url'), name='unique_user_facebook_page'),
        ),
    ]
