# Generated by Django 5.2.16 on 2026-08-30 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageGrowthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.PositiveBigIntegerField(default=0)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='extractor.facebookpage')),
            ],
            options={
                'verbose_name': 'Growth Snapshot',
                'verbose_name_plural': 'Growth Snapshots',
                'ordering': ['-captured_at'],
            },
        ),
    ]
