# Generated by Django 5.2.16 on 2026-10-09 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_pagegrowthsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionjob',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Task ID en Celery / django-celery-results para trazabilidad', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UserExtractorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_refresh_enabled', models.BooleanField(default=True, help_text='Indica si la extracción automática diaria está activa para este usuario.')),
                ('refresh_interval_hours', models.PositiveIntegerField(default=24, help_text='Intervalo de actualización en horas (por defecto 24 horas al cambio de día).')),
                ('last_refresh_at', models.DateTimeField(blank=True, help_text='Última fecha y hora en que se ejecutó la actualización automática para este usuario.', null=True)),
                ('next_refresh_at', models.DateTimeField(blank=True, help_text='Próxima fecha programada para la ejecución automática.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extractor_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Extractor de Usuario',
                'verbose_name_plural': 'Preferencias de Extractor de Usuarios',
            },
        ),
    ]
