# Generated by Django 5.2.16 on 2026-10-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0003_extractionjob_celery_task_id_userextractorpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextractorpreference',
            name='refresh_interval_minutes',
            field=models.PositiveIntegerField(default=1440, help_text='Intervalo de actualización en minutos (1, 5, 15, 30, 60, 1440, etc.).'),
        ),
    ]
