# Generated by Django 6.1 on 2026-09-23 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdownloader', '0004_instagramdownload_comment_count_and_more'),
        ('wordpress_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramdownload',
            name='wp_article_content',
            field=models.TextField(blank=True, help_text='Contenido HTML del artículo en WordPress', null=True),
        ),
        migrations.AddField(
            model_name='instagramdownload',
            name='wp_article_title',
            field=models.CharField(blank=True, help_text='Título del artículo en WordPress', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instagramdownload',
            name='wp_post_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID del post en WordPress', null=True),
        ),
        migrations.AddField(
            model_name='instagramdownload',
            name='wp_post_url',
            field=models.URLField(blank=True, help_text='Permalink directo del artículo publicado en WordPress', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instagramdownload',
            name='wp_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ig_articles', to='wordpress_manager.wordpresssite'),
        ),
    ]
