# Generated by Django 6.1 on 2026-09-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdownloader', '0005_instagramdownload_wp_article_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramdownload',
            name='wp_category',
            field=models.CharField(blank=True, default='Entretenimiento', help_text='Categoría temática del artículo en WordPress (Dramas, Comedia, Entretenimiento)', max_length=100, null=True),
        ),
    ]
