# Generated by Django 6.1 on 2026-09-28 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdownloader', '0006_instagramdownload_wp_category'),
        ('wordpress_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramdownload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='instagramdownload',
            index=models.Index(fields=['user', '-created_at'], name='ig_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramdownload',
            index=models.Index(fields=['-created_at'], name='ig_created_idx'),
        ),
    ]
