# Generated by Django 6.1 on 2026-09-29 01:25

import django.db.models.deletion
import igdownloader.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdownloader', '0007_alter_instagramdownload_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default=igdownloader.models.generate_tracking_slug, help_text='Código identificador único de redirección', max_length=32, unique=True)),
                ('destination_url', models.URLField(help_text='URL de destino final en WordPress', max_length=500)),
                ('total_clicks', models.PositiveIntegerField(default=0, help_text='Total acumulado de clics/visitas recibidas')),
                ('unique_clicks', models.PositiveIntegerField(default=0, help_text='Total de visitantes únicos estimados')),
                ('last_clicked_at', models.DateTimeField(blank=True, help_text='Fecha y hora de la última visita registrada', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download', models.OneToOneField(blank=True, help_text='Descarga/artículo de Instagram asociado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_link', to='igdownloader.instagramdownload')),
                ('user', models.ForeignKey(help_text='Usuario propietario que generó el enlace', on_delete=django.db.models.deletion.CASCADE, related_name='wp_tracking_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enlace de Seguimiento WP',
                'verbose_name_plural': 'Enlaces de Seguimiento WP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('referer', models.CharField(blank=True, default='', max_length=500)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('is_mobile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wp_link_clicks', to=settings.AUTH_USER_MODEL)),
                ('tracking_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='igdownloader.posttrackinglink')),
            ],
            options={
                'verbose_name': 'Clic en Enlace WP',
                'verbose_name_plural': 'Clics en Enlaces WP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='posttrackinglink',
            index=models.Index(fields=['user', '-created_at'], name='wp_track_user_idx'),
        ),
        migrations.AddIndex(
            model_name='posttrackinglink',
            index=models.Index(fields=['slug'], name='wp_track_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='postlinkclick',
            index=models.Index(fields=['user', '-created_at'], name='wp_click_user_idx'),
        ),
        migrations.AddIndex(
            model_name='postlinkclick',
            index=models.Index(fields=['tracking_link', '-created_at'], name='wp_click_link_idx'),
        ),
    ]
