# Generated by Django 6.1 on 2026-09-29 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igdownloader', '0008_posttrackinglink_postlinkclick_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveReaderSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Token único del visitante/pestaña', max_length=64)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('post_title', models.CharField(blank=True, default='', help_text='Título del artículo que está leyendo', max_length=255)),
                ('post_path', models.CharField(blank=True, default='', help_text='Ruta o slug del post (ej: /noticia-drama/)', max_length=255)),
                ('post_url', models.URLField(blank=True, default='', max_length=500)),
                ('country_code', models.CharField(blank=True, default='', max_length=6)),
                ('country_name', models.CharField(blank=True, default='', max_length=100)),
                ('city_name', models.CharField(blank=True, default='', max_length=120)),
                ('device_type', models.CharField(default='mobile', max_length=20)),
                ('os_name', models.CharField(default='android', max_length=30)),
                ('browser_name', models.CharField(default='facebook', max_length=40)),
                ('utm_source', models.CharField(blank=True, default='', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=100)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_ping_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('download', models.ForeignKey(blank=True, help_text='Descarga/artículo asociado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_reader_sessions', to='igdownloader.instagramdownload')),
                ('user', models.ForeignKey(help_text='Usuario propietario/redactor de la publicación', on_delete=django.db.models.deletion.CASCADE, related_name='live_reader_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lector en Vivo WP',
                'verbose_name_plural': 'Lectores en Vivo WP',
                'ordering': ['-last_ping_at'],
                'indexes': [models.Index(fields=['user', '-last_ping_at'], name='wp_live_user_ping_idx'), models.Index(fields=['session_id'], name='wp_live_session_idx'), models.Index(fields=['-last_ping_at'], name='wp_live_ping_idx')],
            },
        ),
    ]
