# Generated by Django 6.1 on 2026-09-30 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igdownloader', '0009_livereadersession'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='livereadersession',
            name='wp_live_user_ping_idx',
        ),
        migrations.RemoveIndex(
            model_name='livereadersession',
            name='wp_live_session_idx',
        ),
        migrations.RemoveIndex(
            model_name='livereadersession',
            name='wp_live_ping_idx',
        ),
        migrations.DeleteModel(
            name='LiveReaderSession',
        ),
    ]
